-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 13:46:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema papelaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `papelaria` ;

-- -----------------------------------------------------
-- Schema papelaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `papelaria` DEFAULT CHARACTER SET utf8 ;
USE `papelaria` ;

-- -----------------------------------------------------
-- Table `papelaria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papelaria`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`venda` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `papelaria`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_venda_cliente1_idx` ON `papelaria`.`venda` (`cliente_id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `papelaria`.`distribuidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`distribuidor` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`distribuidor` (
  `id_distribuidor` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_distribuidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papelaria`.`tipoproduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`tipoproduto` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`tipoproduto` (
  `id_tipoproduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipoproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papelaria`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`Produto` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `quant_produto` INT NULL,
  `preco` FLOAT NULL,
  `descricao` TEXT NULL,
  `tipoproduto_id_tipoproduto` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `fk_Produto_tipoproduto`
    FOREIGN KEY (`tipoproduto_id_tipoproduto`)
    REFERENCES `papelaria`.`tipoproduto` (`id_tipoproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_tipoproduto_idx` ON `papelaria`.`Produto` (`tipoproduto_id_tipoproduto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `papelaria`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`compra` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NULL,
  `distribuidor_id_distribuidor` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_compra_distribuidor1`
    FOREIGN KEY (`distribuidor_id_distribuidor`)
    REFERENCES `papelaria`.`distribuidor` (`id_distribuidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compra_distribuidor1_idx` ON `papelaria`.`compra` (`distribuidor_id_distribuidor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `papelaria`.`Produto_has_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`Produto_has_venda` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`Produto_has_venda` (
  `Produto_id_produto` INT NOT NULL,
  `venda_id_venda` INT NOT NULL,
  PRIMARY KEY (`Produto_id_produto`, `venda_id_venda`),
  CONSTRAINT `fk_Produto_has_venda_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `papelaria`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_venda_venda1`
    FOREIGN KEY (`venda_id_venda`)
    REFERENCES `papelaria`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_has_venda_venda1_idx` ON `papelaria`.`Produto_has_venda` (`venda_id_venda` ASC) VISIBLE;

CREATE INDEX `fk_Produto_has_venda_Produto1_idx` ON `papelaria`.`Produto_has_venda` (`Produto_id_produto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `papelaria`.`Produto_has_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papelaria`.`Produto_has_compra` ;

CREATE TABLE IF NOT EXISTS `papelaria`.`Produto_has_compra` (
  `Produto_id_produto` INT NOT NULL,
  `compra_id_compra` INT NOT NULL,
  PRIMARY KEY (`Produto_id_produto`, `compra_id_compra`),
  CONSTRAINT `fk_Produto_has_compra_Produto1`
    FOREIGN KEY (`Produto_id_produto`)
    REFERENCES `papelaria`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_compra_compra1`
    FOREIGN KEY (`compra_id_compra`)
    REFERENCES `papelaria`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produto_has_compra_compra1_idx` ON `papelaria`.`Produto_has_compra` (`compra_id_compra` ASC) VISIBLE;

CREATE INDEX `fk_Produto_has_compra_Produto1_idx` ON `papelaria`.`Produto_has_compra` (`Produto_id_produto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
